In [37]:
import pandas as pd
import numpy as np
trainFile = "../data/trainDataset/train_3.csv"
df = pd.read_csv(trainFile)
clientsFile="../data/clientesDataset/clientes_clean.csv"
print("Dataset Dimention (Columns, Rows):", df.shape)

print("\n--- First 5 Rows ---")
df.head()

Dataset Dimention (Columns, Rows): (6469, 46)

--- First 5 Rows ---

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,purchase_date,ID,random_noise,is_first_purchase,purchase_year,purchase_month,purchase_day,purchase_dayofweek,purchase_quarter,is_weekend
0,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,...,2024-10-29,10000000,-0.660448,0,2024,10,29,1,4,0
1,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,...,2017-07-08,10000001,0.924510,0,2017,7,8,5,3,1
2,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,...,2019-03-19,10000002,-0.258730,0,2019,3,19,1,1,0
3,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,...,2018-11-10,10000003,1.448402,0,2018,11,10,5,4,1
4,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,...,2021-11-30,10000004,-1.058890,0,2021,11,30,1,4,0

In [38]:
clients_df = pd.read_csv(clientsFile)

# Faz o merge usando os DataFrames `df` e `clients_df`
df_merged = df.merge(clients_df, on="customer_id", how="left")

# Vê as primeiras linhas do resultado
df_merged.head()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,island,municipality,city,postal_area,postal_code,street,address,company_name,customer_since_year,since_2015_or_earlier
0,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,...,(mainland),Municipality MU89: Council of Last Minute Edits,City CY286: Cached Result Falls,Postal area PA228: Hidden Sheet Sector,Postal code PC444: #REF! Delivery Route,Street ST303: Absolute Reference Terrace,Address AD761: Cell Without a Home,Excel Is Not A Database Ltd 1013,2024,0
1,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,...,Island IS8: The Pivot Archipelago,Municipality MU11: Council of Last Minute Edits,City CY147: VLOOKUP Bay,Postal area PA260: Hidden Sheet Sector,Postal code PC636: #REF! Delivery Route,NaN,Address AD382: Cell Without a Home,Excel Is Not A Database Ltd 35,2015,1
2,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,...,(mainland),Municipality MU70: Council of Last Minute Edits,City CY265: Where-less Query Falls,Postal area PA84: Hidden Sheet Sector,Postal code PC200: #REF! Delivery Route,NaN,Address AD723: Cell Without a Home,Excel Is Not A Database Ltd 826,2017,0
3,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,...,Island IS7: The Pivot Archipelago,Municipality MU12: Council of Last Minute Edits,NaN,Postal area PA253: Hidden Sheet Sector,Postal code PC558: #REF! Delivery Route,Street ST144: Last Save Court,Address AD399: Cell Without a Home,Excel Is Not A Database Ltd 530,2018,0
4,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,...,(mainland),Municipality MU142: Council of Last Minute Edits,City CY359: Spill Error Ridge,Postal area PA136: Hidden Sheet Sector,Postal code PC300: #REF! Delivery Route,Street ST395: AutoFill Path,Address AD928: Cell Without a Home,Excel Is Not A Database Ltd 220,2017,0

In [39]:
df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 6469 entries, 0 to 6468
Data columns (total 58 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6469 non-null   int64
 11  days_since_previous_purchase    6469 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       6469 non-null   float64
 16  prior_std_purchase_value        6469 non-null   float64
 17  prior_min_purchase_value        6469 non-null   float64
 18  prior_max_purchase_value        6469 non-null   float64
 19  prior_mean_gap_days             6469 non-null   float64
 20  prior_std_gap_days              6469 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  customer_id                     6469 non-null   int64
 30  payment_type                    6274 non-null   str
 31  salesperson                     6275 non-null   str
 32  commercial_zone                 6469 non-null   str
 33  transport_method                6273 non-null   str
 34  warehouse                       6274 non-null   str
 35  document_series                 6469 non-null   str
 36  purchase_date                   6469 non-null   str
 37  ID                              6469 non-null   int64
 38  random_noise                    6469 non-null   float64
 39  is_first_purchase               6469 non-null   int64
 40  purchase_year                   6469 non-null   int64
 41  purchase_month                  6469 non-null   int64
 42  purchase_day                    6469 non-null   int64
 43  purchase_dayofweek              6469 non-null   int64
 44  purchase_quarter                6469 non-null   int64
 45  is_weekend                      6469 non-null   int64
 46  country_or_region               6469 non-null   str
 47  commercial_region               6434 non-null   str
 48  island                          6465 non-null   str
 49  municipality                    6465 non-null   str
 50  city                            4341 non-null   str
 51  postal_area                     6404 non-null   str
 52  postal_code                     6246 non-null   str
 53  street                          2661 non-null   str
 54  address                         6469 non-null   str
 55  company_name                    6469 non-null   str
 56  customer_since_year             6469 non-null   int64
 57  since_2015_or_earlier           6469 non-null   int64
dtypes: float64(29), int64(12), str(17)
memory usage: 2.9 MB